# TODO: Uncomment this to activate scheduling of this workflow.
#on:
#  schedule:
#  - cron: "0 * * * *"

jobs:
  run-xform:
    runs-on: ubuntu-latest
    name: Run Transformer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Xform
        uses: ./.github/actions/run-xform
        with:
          xform-command: '${GITHUB_WORKSPACE}/src/xform.sh'
      - name: Git Push
        uses: ./.github/actions/git-push
